// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8DUO1zUnQpCWXs134pQymra4BfAax8B4',
    appId: '1:528656991112:web:7f82d3b5a2342f3c71f03d',
    messagingSenderId: '528656991112',
    projectId: 'pulse-recovery-c3abe',
    authDomain: 'pulse-recovery-c3abe.firebaseapp.com',
    storageBucket: 'pulse-recovery-c3abe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsl7btMh0m2XdeyxbcBP-N0hsRWqO92fU',
    appId: '1:528656991112:android:25b8d654a09ce0c271f03d',
    messagingSenderId: '528656991112',
    projectId: 'pulse-recovery-c3abe',
    storageBucket: 'pulse-recovery-c3abe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaAeCRJ2id7QyurHOD0tC9O1yfQBcNXu0',
    appId: '1:528656991112:ios:8c42dda287be576a71f03d',
    messagingSenderId: '528656991112',
    projectId: 'pulse-recovery-c3abe',
    storageBucket: 'pulse-recovery-c3abe.firebasestorage.app',
    iosBundleId: 'com.mycompany.pulserecovery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaAeCRJ2id7QyurHOD0tC9O1yfQBcNXu0',
    appId: '1:528656991112:ios:8c42dda287be576a71f03d',
    messagingSenderId: '528656991112',
    projectId: 'pulse-recovery-c3abe',
    storageBucket: 'pulse-recovery-c3abe.firebasestorage.app',
    iosBundleId: 'com.mycompany.pulserecovery',
  );
}
